### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by paul-michalik**
(1) Ignore whole workspace except requirements (2) set working directFixory to ros (3) source workspace on startup

### CODE REVIEW

**Comment by stefancyliax** [comment]
Docker on windows 10 now works without any issues! Great work!

**Comment by stefancyliax** [comment]
I have to correct myself. There is still an error with the log files.

```
NODES
  /
    dbw_node (twist_controller/dbw_node.py)
    pure_pursuit (waypoint_follower/pure_pursuit)
    styx_server (styx/server.py)
    tl_detector (tl_detector/tl_detector.py)
    waypoint_loader (waypoint_loader/waypoint_loader.py)
    waypoint_updater (waypoint_updater/waypoint_updater.py)

auto-starting new master
process[master]: started with pid [796]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7ebeee72-34b6-11e8-8504-0242ac110002
process[rosout-1]: started with pid [809]
started core service [/rosout]
process[styx_server-2]: started with pid [824]
/usr/bin/env: ‘python\r’: No such file or directory
[styx_server-2] process has died [pid 824, exit code 127, cmd /capstone/ros/src/styx/server.py __name:=styx_server __log:=/root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/styx_server-2.log].
log file: /root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/styx_server-2*.log
process[dbw_node-3]: started with pid [827]
process[waypoint_loader-4]: started with pid [828]
/usr/bin/env: ‘python\r’: No such file or directory
[waypoint_loader-4] process has died [pid 828, exit code 127, cmd /capstone/ros/src/waypoint_loader/waypoint_loader.py __name:=waypoint_loader __log:=/root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/waypoint_loader-4.log].
log file: /root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/waypoint_loader-4*.log
process[pure_pursuit-5]: started with pid [829]
process[waypoint_updater-6]: started with pid [865]
process[tl_detector-7]: started with pid [895]
/usr/bin/env: ‘python\r’: No such file or directory
[tl_detector-7] process has died [pid 895, exit code 127, cmd /capstone/ros/src/tl_detector/tl_detector.py __name:=tl_detector __log:=/root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/tl_detector-7.log].
log file: /root/.ros/log/7ebeee72-34b6-11e8-8504-0242ac110002/tl_detector-7*.log
```

**Comment by stefancyliax** [comment]
Found the error: Has nothing to do with docker. The first line in several python files is 
`#!/usr/bin/env python` 
but since they are written in Windows, they are 
`#!/usr/bin/env python\r`. 
Which a Linux has a problem with. Dumb problem. My git client on windows doesn't even notices the changes.

affects: 
waypoint_updater.py
waypoint_loader.py
tl_detector.py
styx/server.py

Can be fixed with `:set ff=unix` in vim.
https://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory

**Comment by paul-michalik** [comment]
Yes, this is a stupid problem. In Git this is solved via .gitattributes which enforces Unix style line endings for .sh and .py files. In editors or IDEs this must be enforced by the user… ☹

Sent from my Windows 10 phone

**Pull request merged**
