### PR TITLE
Feature/#4 implement tl detector.py

### PR DESCRIPTION
**Pull request by paul-michalik**
OK, the detector is implemented. Tests on synthetic data are green. However, I am unable to run the simulator and the ROS app in sync while using the Windows 10/Docker combo. There seem to be a massive lag in the data transfer - in drive by wire mode the car randomly bumps out of the track after few seconds. Maybe you can run it natively?

### CODE REVIEW

**Comment by stefancyliax** [comment]
I will test it on the local install. 

This sounds a lot like the problem Patrick and I had with the waypoint_updater. There the problem was even more pronounced on the local installation. Which is kind of counter intuitive. 
Problem was that a very minor fault in the waypoint_updater lead to the node publishing very often (depending on system about 280hz) instead of the planned 50hz. So first thing I'll check is rqt_graph..

**Comment by paul-michalik** [comment]
Hm. The traffic light waypoints are published via /traffic_waypoint based on the frequency of published images and vehicle poses. I haven’t changed the logic of the original implementation at all – but it doesn’t seem to be very robust, IMHO.  A /traffic_waypoint is published if a pose and an image were received and if a meaningful traffic light position could be calculated based on this data. From what I can tell, there are no guarantees that these messages match each other in any way…

Sent from my Windows 10 phone

**Comment by stefancyliax** [comment]
Understood. So if tl_detector doesn't find any traffic light, nothing is published?
But even if, the images should be published at a fixed rate, so this doesn't look like the same problem.

**Comment by stefancyliax** [comment]
From my first tests, I could affirm that it isn't a problem with publishing "too frequent". It looks like a performance problem with the inference. After I activate the camera images, the CPU load goes to 100% even on the local machine with an i7. Note that I'm using tensorflow on the CPU for now! There is tensorflow-gpu on the machine but its 1.6, which does not work. 

So now we have a few options i think:
- install tensorflow-gpu 1.3 (have to downgrade CUDA and cuDNN for this)
- improve performance of inference -> smaller image, smaler net, inference optimizer (TensorflowRT)
- use only every x image

**Comment by stefancyliax** [comment]
created issues for next steps. 

Problems have nothing to do with this branch -> can be merged.

**Pull request merged**
